#!/usr/bin/env node
/**
 * new-link.js — create a tracked short link:  https://webetsocial.com/r/<id>
 *
 * Every link 302-redirects to its destination with UTMs attached:
 *   utm_source / utm_medium / utm_campaign  (defaults in links/links.json, overridable per link)
 *   utm_content  (defaults to the link id, overridable)
 *   utm_id       (always the link id, so each link is its own row in GA4)
 *
 * Usage:
 *   node scripts/new-link.js --to /grokbot [--source x] [--medium social] [--campaign betty]
 *                            [--content post_a] [--id custom-id] [--note "what it's for"] [--push]
 *   node scripts/new-link.js --list        # print all links
 *   node scripts/new-link.js --rebuild     # regenerate the /r/ block in _redirects from links.json
 *
 * Without --push it only edits links/links.json + _redirects; commit and push to main to deploy
 * (Netlify auto-deploys main in ~1 min). With --push it commits and pushes for you.
 * Full docs: docs/SHORT-LINKS.md
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const REG = path.join(ROOT, 'links', 'links.json');
const REDIRECTS = path.join(ROOT, '_redirects');
const SITE = 'https://webetsocial.com';
const START = '# >>> SHORT LINKS /r/<id> — generated by scripts/new-link.js from links/links.json. Do not edit by hand.';
const END = '# <<< SHORT LINKS END';
const ID_RE = /^[A-Za-z0-9][A-Za-z0-9_-]{1,39}$/;
const VAL_RE = /^[A-Za-z0-9][A-Za-z0-9_.-]{0,99}$/;
const ALPHA = 'abcdefghijkmnopqrstuvwxyz23456789'; // no l/1/0/o — easy to read aloud

function args(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (!a.startsWith('--')) continue;
    const k = a.slice(2);
    const next = argv[i + 1];
    if (next === undefined || next.startsWith('--')) out[k] = true;
    else { out[k] = next; i++; }
  }
  return out;
}

function load() { return JSON.parse(fs.readFileSync(REG, 'utf8')); }
function save(reg) { fs.writeFileSync(REG, JSON.stringify(reg, null, 2) + '\n'); }

function newId(taken) {
  for (;;) {
    const bytes = crypto.randomBytes(6);
    let id = '';
    for (const b of bytes) id += ALPHA[b % ALPHA.length];
    if (!taken.has(id)) return id;
  }
}

function destination(link, defaults) {
  const raw = String(link.to);
  const external = /^https:\/\//i.test(raw);
  if (!external && !raw.startsWith('/')) throw new Error(`"to" must start with / or https:// (got ${raw})`);
  if (raw.startsWith('//')) throw new Error('"to" cannot start with //');
  const u = new URL(raw, SITE);
  const utm = {
    utm_source: link.utm_source || defaults.utm_source,
    utm_medium: link.utm_medium || defaults.utm_medium,
    utm_campaign: link.utm_campaign || defaults.utm_campaign,
    utm_content: link.utm_content || link.id,
    utm_id: link.id,
  };
  for (const [k, v] of Object.entries(utm)) {
    if (!VAL_RE.test(String(v))) throw new Error(`${k} "${v}" must be letters, numbers, _ . - only`);
    u.searchParams.set(k, v);
  }
  const s = u.toString();
  return external ? s : s.slice(SITE.length);
}

function rebuild(reg) {
  const lines = [START];
  for (const l of reg.links) {
    const d = destination(l, reg.defaults);
    lines.push(`/r/${l.id}   ${d}  302`);
    lines.push(`/r/${l.id}/  ${d}  302`);
  }
  lines.push('# Unknown /r/ ids fall back to the homepage instead of a 404.');
  lines.push('/r/*  /  302');
  lines.push(END);
  const block = lines.join('\n');
  let s = fs.readFileSync(REDIRECTS, 'utf8');
  const a = s.indexOf(START), b = s.indexOf(END);
  if (a >= 0 && b > a) s = s.slice(0, a) + block + s.slice(b + END.length);
  else s = s.replace(/\s*$/, '\n\n') + block + '\n';
  fs.writeFileSync(REDIRECTS, s);
}

function main() {
  const o = args(process.argv.slice(2));
  const reg = load();
  if (o.list) {
    for (const l of reg.links) console.log(`${SITE}/r/${l.id}  ->  ${destination(l, reg.defaults)}${l.note ? '   # ' + l.note : ''}`);
    return;
  }
  if (o.rebuild) { rebuild(reg); console.log('Rebuilt /r/ block from', reg.links.length, 'links.'); return; }
  if (!o.to || o.to === true) { console.error('Missing --to (e.g. --to /grokbot). See docs/SHORT-LINKS.md'); process.exit(1); }

  const taken = new Set(reg.links.map((l) => l.id));
  let id = o.id && o.id !== true ? String(o.id) : newId(taken);
  if (!ID_RE.test(id)) { console.error(`Bad --id "${id}" (letters, numbers, _ -, 2-40 chars)`); process.exit(1); }
  if (taken.has(id)) { console.error(`Link id "${id}" already exists.`); process.exit(1); }

  const link = { id, to: String(o.to) };
  if (o.source) link.utm_source = String(o.source);
  if (o.medium) link.utm_medium = String(o.medium);
  if (o.campaign) link.utm_campaign = String(o.campaign);
  if (o.content) link.utm_content = String(o.content);
  if (o.note) link.note = String(o.note);
  link.created = new Date().toISOString();

  const dest = destination(link, reg.defaults); // validates before saving
  reg.links.push(link);
  save(reg);
  rebuild(reg);
  console.log(`${SITE}/r/${id}`);
  console.log(`  -> ${dest}`);

  if (o.push) {
    execSync('git add links/links.json _redirects', { cwd: ROOT, stdio: 'inherit' });
    execSync(`git commit -q -m "Short link /r/${id} -> ${link.to}"`, { cwd: ROOT, stdio: 'inherit' });
    execSync('git push -q origin main', { cwd: ROOT, stdio: 'inherit' });
    console.log('  Pushed to main; live in about a minute.');
  } else {
    console.log('  Not deployed yet: commit links/links.json + _redirects and push to main (or rerun with --push).');
  }
}

main();
